import crypto from "crypto";
import type { PoolClient } from "pg";
import type { PortalUser } from "./auth";
import { transaction } from "./db";
import { PortalError,requiredText } from "./portal-security";

const num=(v:unknown,n:string)=>{const x=Number(v);if(!Number.isSafeInteger(x)||x<=0)throw new PortalError(400,`${n} is invalid`,"VALIDATION_ERROR");return x;};
async function audit(c:PoolClient,u:PortalUser,action:string,type:string,eid:string,before:unknown,after:unknown,cid:string,sid?:number){await c.query(`INSERT INTO portal_audit_logs(user_id,student_id,action,entity_type,entity_id,before_state,after_state,correlation_id) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7::jsonb,$8::uuid)`,[u.id,sid??null,action,type,eid,JSON.stringify(before??null),JSON.stringify(after??null),cid]);}

export async function addLogbook(raw:any,actor:PortalUser,cid:string){const placementId=num(raw.placementId,"placementId");return transaction(async c=>{const p=await c.query<{student_id:number;status:string}>(`SELECT ap.student_id,ap.status FROM portal_attachment_placements ap LEFT JOIN portal_students s ON s.id=ap.student_id WHERE ap.id=$1 AND ($2::boolean OR s.user_id=$3) FOR UPDATE`,[placementId,actor.permissions.includes("attachment.evaluate")||actor.roles.includes("super_admin"),actor.id]);if(!p.rowCount)throw new PortalError(404,"Placement not found or not owned by this student","NOT_FOUND");if(p.rows[0].status!=="active"&&p.rows[0].status!=="assigned")throw new PortalError(409,"Placement does not accept logbook entries","INVALID_TRANSITION");
 const entry=await c.query(`INSERT INTO portal_attachment_logbook_entries(placement_id,entry_date,started_at,ended_at,activities,competencies,student_notes) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[placementId,requiredText(raw.entryDate,"Entry date",10),requiredText(raw.startedAt,"Start time",8),requiredText(raw.endedAt,"End time",8),requiredText(raw.activities,"Activities",4000),String(raw.competencies??"").trim()||null,String(raw.studentNotes??"").trim()||null]);await c.query("UPDATE portal_attachment_placements SET status='active',updated_at=now() WHERE id=$1",[placementId]);await audit(c,actor,"attachment.logbook_submitted","attachment_logbook",String(entry.rows[0].id),null,entry.rows[0],cid,p.rows[0].student_id);return entry.rows[0];});}

export async function evaluateAttachment(raw:any,actor:PortalUser,cid:string){const placementId=num(raw.placementId,"placementId");const fields=["clinicalCompetence","professionalConduct","communication","infectionPrevention","documentation","attendance"] as const;const scores=fields.map(f=>{const x=Number(raw[f]);if(!Number.isInteger(x)||x<0||x>100)throw new PortalError(400,`${f} must be between 0 and 100`,"VALIDATION_ERROR");return x;});return transaction(async c=>{const p=await c.query<{student_id:number;status:string;required_hours:string}>("SELECT student_id,status,required_hours::text FROM portal_attachment_placements WHERE id=$1 FOR UPDATE",[placementId]);if(!p.rowCount)throw new PortalError(404,"Placement not found","NOT_FOUND");const hours=await c.query<{hours:string}>(`SELECT COALESCE(sum(extract(epoch FROM (ended_at-started_at))/3600),0)::text hours FROM portal_attachment_logbook_entries WHERE placement_id=$1 AND supervisor_status='approved'`,[placementId]);if(Number(hours.rows[0].hours)<Number(p.rows[0].required_hours))throw new PortalError(409,`Only ${Number(hours.rows[0].hours).toFixed(1)} of ${p.rows[0].required_hours} required approved hours are complete`,"INSUFFICIENT_HOURS");const evaluation=await c.query(`INSERT INTO portal_attachment_evaluations(placement_id,clinical_competence,professional_conduct,communication,infection_prevention,documentation,attendance,recommendation,supervisor_name,verified_by,verified_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,now()) ON CONFLICT(placement_id) DO UPDATE SET clinical_competence=excluded.clinical_competence,professional_conduct=excluded.professional_conduct,communication=excluded.communication,infection_prevention=excluded.infection_prevention,documentation=excluded.documentation,attendance=excluded.attendance,recommendation=excluded.recommendation,supervisor_name=excluded.supervisor_name,verified_by=excluded.verified_by,verified_at=now() RETURNING *`,[placementId,...scores,requiredText(raw.recommendation,"Recommendation",2000),requiredText(raw.supervisorName,"Supervisor name"),actor.id]);await c.query("UPDATE portal_attachment_placements SET status='completed',verified_by=$2,verified_at=now() WHERE id=$1",[placementId,actor.id]);await audit(c,actor,"attachment.evaluated","attachment",String(placementId),p.rows[0],evaluation.rows[0],cid,p.rows[0].student_id);return evaluation.rows[0];});}

const permissionFor=(title:string)=>title.toLowerCase().includes("finance")?"clearance.finance":title.toLowerCase().includes("library")?"clearance.library":title.toLowerCase().includes("skills")?"clearance.skills_lab":title.toLowerCase().includes("attachment")?"clearance.attachment":title.toLowerCase().includes("academic")?"clearance.academic":"clearance.registrar";
export async function decideClearance(raw:any,actor:PortalUser,cid:string){const clearanceId=num(raw.clearanceId,"clearanceId");const decision=requiredText(raw.decision,"Decision",20);if(!["approved","revoked","rejected"].includes(decision))throw new PortalError(400,"Invalid clearance decision","VALIDATION_ERROR");const reason=requiredText(raw.reason,"Reason",1000);return transaction(async c=>{const found=await c.query<{student_id:number;status:string;title:string}>(`SELECT sc.student_id,sc.status,cp.title FROM portal_student_clearance sc JOIN portal_clearance_checkpoints cp ON cp.id=sc.checkpoint_id WHERE sc.id=$1 FOR UPDATE`,[clearanceId]);if(!found.rowCount)throw new PortalError(404,"Clearance checkpoint not found","NOT_FOUND");const required=permissionFor(found.rows[0].title);if(!actor.permissions.includes(required)&&!actor.roles.includes("super_admin"))throw new PortalError(403,`Permission ${required} is required`,"FORBIDDEN");if(required==="clearance.registrar"&&decision==="approved"){const pending=await c.query<{count:string}>("SELECT count(*)::text count FROM portal_student_clearance WHERE student_id=$1 AND id<>$2 AND status<>'approved'",[found.rows[0].student_id,clearanceId]);const holds=await c.query<{count:string}>("SELECT count(*)::text count FROM portal_student_holds WHERE student_id=$1 AND status='active'",[found.rows[0].student_id]);if(Number(pending.rows[0].count)>0||Number(holds.rows[0].count)>0)throw new PortalError(409,"All departments must approve and all holds must be released before registrar clearance","CLEARANCE_DEPENDENCY");}
 const updated=await c.query("UPDATE portal_student_clearance SET status=$2,approved_by=CASE WHEN $2='approved' THEN $3::uuid ELSE NULL END,approved_at=CASE WHEN $2='approved' THEN now() ELSE NULL END,notes=$4 WHERE id=$1 RETURNING *",[clearanceId,decision,actor.id,reason]);await c.query("INSERT INTO portal_clearance_decisions(student_clearance_id,decision,reason,decided_by) VALUES($1,$2,$3,$4)",[clearanceId,decision,reason,actor.id]);await audit(c,actor,"clearance.decided","clearance",String(clearanceId),found.rows[0],updated.rows[0],cid,found.rows[0].student_id);return updated.rows[0];});}

async function eligibility(c:PoolClient,studentId:number){const checks=await c.query<{enrollment_complete:boolean;modules_complete:boolean;attachment_complete:boolean;finance_clear:boolean;clearance_complete:boolean;no_holds:boolean}>(`SELECT
 EXISTS(SELECT 1 FROM portal_student_enrollments WHERE student_id=$1 AND status='completed') enrollment_complete,
 NOT EXISTS(SELECT 1 FROM portal_program_modules pm JOIN portal_student_enrollments e ON e.program_id=pm.program_id AND e.student_id=$1 LEFT JOIN portal_module_results mr ON mr.enrollment_id=e.id AND mr.module_id=pm.module_id AND mr.outcome='passed' WHERE mr.id IS NULL) modules_complete,
 EXISTS(SELECT 1 FROM portal_attachment_placements WHERE student_id=$1 AND status='completed' AND verified_at IS NOT NULL) attachment_complete,
 NOT EXISTS(SELECT 1 FROM portal_invoices i WHERE i.student_id=$1 AND i.deleted_at IS NULL AND i.status NOT IN ('paid','void')) finance_clear,
 NOT EXISTS(SELECT 1 FROM portal_student_clearance WHERE student_id=$1 AND status<>'approved') clearance_complete,
 NOT EXISTS(SELECT 1 FROM portal_student_holds WHERE student_id=$1 AND status='active') no_holds`,[studentId]);const row=checks.rows[0];const reasons=Object.entries(row).filter(([,v])=>!v).map(([k])=>k);return{eligible:reasons.length===0,reasons,checks:row};}
export async function addGraduationCandidate(raw:any,actor:PortalUser,cid:string){const studentId=num(raw.studentId,"studentId"),batchId=num(raw.batchId,"batchId");return transaction(async c=>{const e=await eligibility(c,studentId);if(!e.eligible)throw new PortalError(409,`Student is not eligible: ${e.reasons.join(", ")}`,"NOT_ELIGIBLE");const candidate=await c.query(`INSERT INTO portal_graduation_candidates(batch_id,student_id,status,clearance_completed,registrar_approved_by,registrar_approved_at,eligibility_snapshot,eligibility_checked_at) VALUES($1,$2,'eligible',true,$3,now(),$4::jsonb,now()) ON CONFLICT(batch_id,student_id) DO UPDATE SET status='eligible',clearance_completed=true,registrar_approved_by=excluded.registrar_approved_by,registrar_approved_at=now(),eligibility_snapshot=excluded.eligibility_snapshot,eligibility_checked_at=now() RETURNING *`,[batchId,studentId,actor.id,JSON.stringify(e)]);await audit(c,actor,"graduation.candidate_approved","graduation_candidate",`${batchId}:${studentId}`,null,candidate.rows[0],cid,studentId);return candidate.rows[0];});}
export async function issueCredentials(raw:any,actor:PortalUser,cid:string){const studentId=num(raw.studentId,"studentId"),batchId=num(raw.batchId,"batchId");return transaction(async c=>{const candidate=await c.query("SELECT * FROM portal_graduation_candidates WHERE student_id=$1 AND batch_id=$2 FOR UPDATE",[studentId,batchId]);if(!candidate.rowCount||candidate.rows[0].status!=="eligible"||!candidate.rows[0].registrar_approved_at)throw new PortalError(409,"An approved eligible graduation candidate is required","NOT_ELIGIBLE");const current=await eligibility(c,studentId);if(!current.eligible)throw new PortalError(409,`Eligibility changed: ${current.reasons.join(", ")}`,"NOT_ELIGIBLE");const year=new Date().getFullYear();const issued=[];for(const type of ["certificate","transcript"]){const serial=`RHTI-${type==='certificate'?'CERT':'TR'}-${year}-${crypto.randomBytes(5).toString('hex').toUpperCase()}`;const credential=await c.query("INSERT INTO portal_credentials(student_id,batch_id,credential_type,serial_number,issued_by,metadata) VALUES($1,$2,$3,$4,$5,$6::jsonb) RETURNING id,credential_type,serial_number,verification_code",[studentId,batchId,type,serial,actor.id,JSON.stringify({eligibility:current})]);issued.push(credential.rows[0]);}await c.query("UPDATE portal_graduation_candidates SET status='graduated',updated_at=now() WHERE student_id=$1 AND batch_id=$2",[studentId,batchId]);await c.query("UPDATE portal_student_enrollments SET status='graduated',completed_at=COALESCE(completed_at,now()) WHERE student_id=$1 AND status='completed'",[studentId]);await c.query("UPDATE portal_students SET status='graduated' WHERE id=$1",[studentId]);await audit(c,actor,"graduation.credentials_issued","student",String(studentId),candidate.rows[0],issued,cid,studentId);return{studentId,batchId,credentials:issued};});}
