import crypto from 'crypto';
import {query,transaction} from './db';
import {normalizeEmail} from './portal-security';
import{normalizeWhatsAppPhone,sendSchoolDocument,sendSchoolTemplate,sendSchoolText}from'./school-whatsapp-meta';

type Context={fullName?:string;email?:string;program?:string;kcseGrade?:string;kcseYear?:string;dateOfBirth?:string};
const applyWords=/\b(apply|application|enrol|enroll|admission)\b/i;
const statusWords=/\b(status|application update|check application)\b/i;
const cancelWords=/^(cancel|stop|exit|restart)$/i;
const fields:Array<[keyof Context,string,string]>=[['fullName','full_name','Please send your full legal name.'],['email','email','What is your email address?'],['program','program','Choose a program: CNA, HRIT, or Dental Assistant.'],['kcseGrade','kcse_grade','What was your KCSE mean grade?'],['kcseYear','kcse_year','What year did you complete KCSE?'],['dateOfBirth','date_of_birth','Send your date of birth as YYYY-MM-DD.']];

async function log(phone:string,direction:'inbound'|'outbound',status:string,body:string,messageId?:string,payload:unknown={}){const result=await query(`INSERT INTO portal_whatsapp_messages(provider_message_id,phone,direction,message_type,body,status,payload) VALUES(NULLIF($1,''),$2,$3,'text',$4,$5,$6::jsonb) ON CONFLICT(provider_message_id) DO NOTHING RETURNING id`,[messageId||'',phone,direction,body,status,JSON.stringify(payload)]);return Boolean(result.rowCount);}
async function reply(phone:string,text:string,status='sent'){const result=await sendSchoolText(phone,text);await log(phone,'outbound',status,text,result?.messages?.[0]?.id,'');return result;}
async function session(phone:string){const result=await query<any>('SELECT state,context FROM portal_whatsapp_conversations WHERE phone=$1',[phone]);return result.rows[0]??{state:'idle',context:{}};}
async function save(phone:string,state:string,context:Context){await query(`INSERT INTO portal_whatsapp_conversations(phone,state,context,last_inbound_at,updated_at) VALUES($1,$2,$3::jsonb,now(),now()) ON CONFLICT(phone) DO UPDATE SET state=excluded.state,context=excluded.context,last_inbound_at=now(),updated_at=now()`,[phone,state,JSON.stringify(context)]);}
const normalizeProgram=(value:string)=>/cna|nurs/i.test(value)?'cna':/hrit|health|record/i.test(value)?'hrit':/dental/i.test(value)?'dental':'';
function validate(field:keyof Context,value:string){const text=value.trim();if(field==='email')return normalizeEmail(text);if(field==='program'){const p=normalizeProgram(text);if(!p)throw new Error('Please choose CNA, HRIT, or Dental Assistant.');return p;}if(field==='kcseYear'&&!/^(19|20)\d{2}$/.test(text))throw new Error('Send a valid four-digit KCSE year.');if(field==='dateOfBirth'&&!/^\d{4}-\d{2}-\d{2}$/.test(text))throw new Error('Use YYYY-MM-DD for the date of birth.');if(!text||text.length>150)throw new Error('Please send a valid response.');return text;}

async function knowledge(){const [programs,faq]=await Promise.all([query<any>('SELECT slug,title,duration,entry_requirements,tuition_fee_kes,overview FROM rhti_programs ORDER BY display_order'),query<any>('SELECT topic,answer FROM rhti_knowledge_base ORDER BY display_order')]);return JSON.stringify({institution:'Radiant Hospital Training Institute (RHTI), Kasarani Sportsview, Nairobi',phone:'0712 588 588',email:'rhti@radianthospitals.org',programs:programs.rows,faq:faq.rows});}
async function answerInquiry(message:string,history:Context){const key=process.env.GEMINI_API_KEY?.trim();if(!key)return 'I can help with RHTI programs, fees, requirements, intakes, attachments, location, and applications. Reply APPLY to begin an application.';const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),Number(process.env.GEMINI_TIMEOUT_SECONDS||15)*1000);try{const response=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(process.env.GEMINI_MODEL||'gemini-2.5-flash-lite')}:generateContent`,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':key},signal:controller.signal,body:JSON.stringify({systemInstruction:{parts:[{text:`You are the official RHTI WhatsApp admissions assistant. Answer only from this verified database context: ${await knowledge()}. Be concise, friendly, and factual. Never invent dates, fees, accreditation, admission decisions, or guarantees. Do not collect sensitive data except during the explicit application workflow. For medical questions, state that you provide school information only. Invite the user to reply APPLY when appropriate.`}]},contents:[{role:'user',parts:[{text:message}]}],generationConfig:{temperature:.15,maxOutputTokens:350}})});const data=await response.json();if(!response.ok)throw new Error('Gemini request failed');return data?.candidates?.[0]?.content?.parts?.map((p:any)=>p.text||'').join('').trim()||'Please contact RHTI admissions on 0712 588 588.';}catch{return 'I can help with RHTI programs, fees, requirements, intakes, attachments, location, and applications. Reply APPLY to begin an application.';}finally{clearTimeout(timeout);}}

async function createApplication(phone:string,c:Required<Context>){return transaction(async client=>{const program=await client.query<any>('SELECT id,slug FROM portal_programs WHERE slug=$1 AND status=\'active\'',[c.program]);if(!program.rowCount)throw new Error('That program is not currently available.');const intake=await client.query<any>("SELECT id FROM portal_intakes WHERE status='open' ORDER BY intake_year,intake_month LIMIT 1");const row=await client.query<any>(`INSERT INTO applications(full_name,email,phone,date_of_birth,program,program_id,intake_id,kcse_mean_grade,kcse_year,status,source,notes,chat_session_id) VALUES($1,$2,$3,$4::date,$5,$6,$7,$8,$9,'new','whatsapp','Submitted with explicit WhatsApp applicant confirmation',$10) RETURNING id`,[c.fullName,c.email,phone,c.dateOfBirth,c.program,program.rows[0].id,intake.rows[0]?.id??null,c.kcseGrade,Number(c.kcseYear),`whatsapp:${phone}`]);return row.rows[0].id;});}

export async function handleSchoolWhatsApp(phoneRaw:string,textRaw:string,messageId?:string,payload:unknown={}){const phone=normalizeWhatsAppPhone(phoneRaw),text=textRaw.trim();if(!phone||!text)return;if(!await log(phone,'inbound','received',text,messageId,payload))return;const s=await session(phone);if(cancelWords.test(text)){await save(phone,'idle',{});return reply(phone,'Cancelled. Ask another question or reply APPLY whenever you are ready.');}if(statusWords.test(text)){const found=await query<any>(`SELECT id,status,full_name FROM applications WHERE phone=$1 AND deleted_at IS NULL ORDER BY created_at DESC LIMIT 1`,[phone]);return reply(phone,found.rowCount?`${found.rows[0].full_name}, application RHTI-${found.rows[0].id} is ${String(found.rows[0].status).replace('_',' ')}.`:'I could not find an application for this WhatsApp number.');}if(s.state==='confirm_application'){if(!/^(yes|confirm|submit)$/i.test(text)){await save(phone,'idle',{});return reply(phone,'Application not submitted. Reply APPLY to start again.');}try{const id=await createApplication(phone,s.context as Required<Context>);await save(phone,'idle',{});await reply(phone,`Application received successfully. Your reference is RHTI-${id}. We will send updates to this WhatsApp number.`,'application_created');return;}catch(error){await save(phone,'idle',{});return reply(phone,error instanceof Error&&/unique|duplicate/i.test(error.message)?'An active application already exists for these details. Reply STATUS to check it.':'I could not submit the application. Please contact admissions on 0712 588 588.','application_failed');}}
  if(s.state.startsWith('collect_')){const field=s.state.slice(8) as keyof Context;let value;try{value=validate(field,text);}catch(error){return reply(phone,error instanceof Error?error.message:'Please try again.');}const context={...s.context,[field]:value};const index=fields.findIndex(([key])=>key===field);const next=fields[index+1];if(next){await save(phone,`collect_${next[0]}`,context);return reply(phone,next[2]);}await save(phone,'confirm_application',context);return reply(phone,`Please confirm your application:\nName: ${context.fullName}\nEmail: ${context.email}\nProgram: ${String(context.program).toUpperCase()}\nKCSE: ${context.kcseGrade} (${context.kcseYear})\nDOB: ${context.dateOfBirth}\n\nReply CONFIRM to submit or CANCEL.`);}
  if(applyWords.test(text)){await save(phone,'collect_fullName',{});return reply(phone,fields[0][2]);}return reply(phone,await answerInquiry(text,s.context),'ai_reply_sent');}

async function offerToken(applicationId:number){const token=crypto.randomBytes(32).toString('hex'),hash=crypto.createHash('sha256').update(token).digest('hex');await transaction(async c=>{await c.query('UPDATE portal_offer_documents SET revoked_at=now() WHERE application_id=$1 AND revoked_at IS NULL',[applicationId]);await c.query('INSERT INTO portal_offer_documents(application_id,access_token_hash,expires_at) VALUES($1,$2,now()+interval \'30 days\')',[applicationId,hash]);});return token;}
export async function dispatchWhatsAppOutbox(limit=10){const claimed=await transaction(async c=>(await c.query<any>(`WITH jobs AS(SELECT id FROM portal_whatsapp_outbox WHERE ((status IN ('pending','failed') AND available_at<=now()) OR (status='processing' AND locked_at<now()-interval '5 minutes')) AND attempts<6 ORDER BY id FOR UPDATE SKIP LOCKED LIMIT $1) UPDATE portal_whatsapp_outbox o SET status='processing',locked_at=now(),attempts=attempts+1,updated_at=now() FROM jobs WHERE o.id=jobs.id RETURNING o.*`,[limit])).rows);for(const job of claimed){try{const app=(await query<any>(`SELECT a.*,p.title program_title FROM applications a LEFT JOIN portal_programs p ON p.id=a.program_id WHERE a.id=$1`,[job.application_id])).rows[0];const parameters=[app.full_name,`RHTI-${app.id}`,String(app.status).replace('_',' ')];let result;if(job.message_kind==='offer_letter'){const token=await offerToken(app.id),base=(process.env.PUBLIC_APP_URL||process.env.APP_URL||'').replace(/\/$/,'');const link=`${base}/api/whatsapp/offers/${token}`;const template=process.env.SCHOOL_WHATSAPP_OFFER_TEMPLATE;if(template)result=await sendSchoolTemplate(job.destination,template,parameters,link);else result=await sendSchoolDocument(job.destination,link,`RHTI-${app.id}-Offer.pdf`,`Offer letter for application RHTI-${app.id}`);}else{const template=job.template_name||process.env.SCHOOL_WHATSAPP_STATUS_TEMPLATE;if(template)result=await sendSchoolTemplate(job.destination,template,parameters);else result=await sendSchoolText(job.destination,`${app.full_name}, application RHTI-${app.id} is now ${String(app.status).replace('_',' ')}.`);}await query("UPDATE portal_whatsapp_outbox SET status='sent',sent_at=now(),last_error=NULL,updated_at=now() WHERE id=$1",[job.id]);await log(job.destination,'outbound','sent',job.message_kind,result?.messages?.[0]?.id,result);}catch(error){await query("UPDATE portal_whatsapp_outbox SET status='failed',available_at=now()+(LEAST(attempts,6)||' minutes')::interval,last_error=$2,updated_at=now() WHERE id=$1",[job.id,error instanceof Error?error.message:'Delivery failed']);}}return claimed.length;}
